/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.facens.upx2.smartgarden.view.form;

import com.facens.upx2.smartgarden.controller.CropTypesController;
import com.facens.upx2.smartgarden.controller.helper.CropTypesControllerHelper;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Gustavo Rosendo Cardoso
 */
public class CropTypesScreen extends javax.swing.JFrame {
        
    private CropTypesController cropTypesController;
    private CropTypesControllerHelper cropTypesControllerHelper;
    private Long institutionId;
        
    /**
     * Creates new form CropTypesScreen
     */
    public CropTypesScreen(long institutionId){
        setUndecorated(true); 
        initComponents();  
                
        setSize(1600, 754);
        setLocationRelativeTo(null);
        setResizable(false);
        
        this.cropTypesControllerHelper = new CropTypesControllerHelper(this);
        this.cropTypesController = new CropTypesController(cropTypesControllerHelper, this);
        
        this.institutionId = institutionId;
        
        this.loadData(this.institutionId);
        
        BackgroundImage.setIcon( new javax.swing.ImageIcon( getClass().getResource("/com/facens/upx2/smartgarden/view/images/CropTypes.png") ) );
        
        jButtonBack.setOpaque(false);
        jButtonBack.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jButtonBack.setBorder(null); 
        
        jDeleteButton.setOpaque(false);
        jDeleteButton.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jDeleteButton.setBorder(null); 
        
        jButtonRegister.setOpaque(false);
        jButtonRegister.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jButtonRegister.setBorder(null); 
        
        jSearchButton.setOpaque(false);
        jSearchButton.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jSearchButton.setBorder(null); 
        
        jNameTextField1.setOpaque(false);
        jNameTextField1.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jNameTextField1.setBorder(null); 
        
        jStartDateTextField.setOpaque(false);
        jStartDateTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jStartDateTextField.setBorder(null); 
        
        jEndDateTextField.setOpaque(false);
        jEndDateTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jEndDateTextField.setBorder(null); 
        
        jSearchTextField.setOpaque(false);
        jSearchTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jSearchTextField.setBorder(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jStartDateTextField = new javax.swing.JTextField();
        jNameTextField1 = new javax.swing.JTextField();
        jSearchTextField = new javax.swing.JTextField();
        jSearchButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jEndDateTextField = new javax.swing.JTextField();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 754));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 170, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Data inicial de plantio apropriada", "Data final de plantio apropriada", "Data"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 940, 360));

        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 40, 40));
        getContentPane().add(jStartDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 144, 290, 30));
        getContentPane().add(jNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 144, 290, 30));
        getContentPane().add(jSearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 325, 827, 30));

        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 325, 32, 30));

        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 325, 32, 30));
        getContentPane().add(jEndDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(944, 144, 290, 30));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/facens/upx2/smartgarden/view/images/CropTypes.png"))); // NOI18N
        getContentPane().add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 754));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        String name = this.getjNameTextField1().getText();
        String startDate = this.getjStartDateTextField().getText();
        String endDate = this.getjEndDateTextField().getText();
        
        this.cropTypesController.registerCropType(name, startDate, endDate, this.institutionId);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        String search = this.getjSearchTextField().getText();
        
        this.loadDataWithSearch(this.institutionId, search);
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        cropTypesController.deleteSelectedCropType(this.institutionId);
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JTextField jEndDateTextField;
    private javax.swing.JTextField jNameTextField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchTextField;
    private javax.swing.JTextField jStartDateTextField;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void loadData(long institutionId){
        this.cropTypesController.loadCropTypes(institutionId);
    }
    
    private void loadDataWithSearch(long institutionId, String search){
        this.cropTypesController.loadCropTypesWithSearch(institutionId, search);
    }

    public JTable getTableCropTypes() {
        return jTable1;
    }

    public void setTableCropTypes(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextField getjSearchTextField() {
        return jSearchTextField;
    }

    public void setjSearchTextField(JTextField jSearchTextField) {
        this.jSearchTextField = jSearchTextField;
    }

    public JTextField getjNameTextField1() {
        return jNameTextField1;
    }

    public void setjNameTextField1(JTextField jNameTextField1) {
        this.jNameTextField1 = jNameTextField1;
    }

    public JTextField getjEndDateTextField() {
        return jEndDateTextField;
    }

    public void setjEndDateTextField(JTextField jEndDateTextField) {
        this.jEndDateTextField = jEndDateTextField;
    }

    public JTextField getjStartDateTextField() {
        return jStartDateTextField;
    }

    public void setjStartDateTextField(JTextField jStartDateTextField) {
        this.jStartDateTextField = jStartDateTextField;
    }
    
    public void clearInputs(){
        jNameTextField1.setText("");
        jStartDateTextField.setText("");
        jEndDateTextField.setText("");
        jSearchTextField.setText("");
    }
}
