/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.facens.upx2.smartgarden.view.form;

import com.facens.upx2.smartgarden.controller.CropTypesController;
import com.facens.upx2.smartgarden.controller.helper.CropTypesControllerHelper;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Gustavo Rosendo Cardoso
 */
public class CropTypesScreen extends javax.swing.JFrame {
        
    private CropTypesController cropTypesController;
    private CropTypesControllerHelper cropTypesControllerHelper;
    private Long institutionId;
        
    /**
     * Creates new form CropTypesScreen
     */
    public CropTypesScreen(long institutionId){
        setUndecorated(true); 
        initComponents();  
                
        setSize(1600, 754);
        setLocationRelativeTo(null);
        setResizable(false);
        
        this.cropTypesControllerHelper = new CropTypesControllerHelper(this);
        this.cropTypesController = new CropTypesController(cropTypesControllerHelper, this);
        
        this.institutionId = institutionId;
        
        this.loadData(this.institutionId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jStartDateTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jNameTextField1 = new javax.swing.JTextField();
        jSearchTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSearchButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jEndDateTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 754));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegister.setText("Cadastrar Tipo Plantio");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Data inicial de plantio apropriada", "Data final de plantio apropriada", "Data"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 1580, 340));

        jButtonBack.setText("Voltar");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        getContentPane().add(jStartDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 300, -1));

        jLabel5.setText("Data inicial de plantio apropriada");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));
        getContentPane().add(jNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, -1));
        getContentPane().add(jSearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 170, -1));

        jLabel9.setText("Pesquisar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jSearchButton.setText("Buscar");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jDeleteButton.setText("Excluir Tipo Plantio Selecionado");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, -1, -1));
        getContentPane().add(jEndDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 300, -1));

        jLabel10.setText("Data final de plantio apropriada");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        String name = this.getjNameTextField1().getText();
        String startDate = this.getjStartDateTextField().getText();
        String endDate = this.getjEndDateTextField().getText();
        
        this.cropTypesController.registerCropType(name, startDate, endDate, this.institutionId);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        String search = this.getjSearchTextField().getText();
        
        this.loadDataWithSearch(this.institutionId, search);
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        cropTypesController.deleteSelectedCropType(this.institutionId);
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JTextField jEndDateTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNameTextField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchTextField;
    private javax.swing.JTextField jStartDateTextField;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void loadData(long institutionId){
        this.cropTypesController.loadCropTypes(institutionId);
    }
    
    private void loadDataWithSearch(long institutionId, String search){
        this.cropTypesController.loadCropTypesWithSearch(institutionId, search);
    }

    public JTable getTableCropTypes() {
        return jTable1;
    }

    public void setTableCropTypes(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextField getjSearchTextField() {
        return jSearchTextField;
    }

    public void setjSearchTextField(JTextField jSearchTextField) {
        this.jSearchTextField = jSearchTextField;
    }

    public JTextField getjNameTextField1() {
        return jNameTextField1;
    }

    public void setjNameTextField1(JTextField jNameTextField1) {
        this.jNameTextField1 = jNameTextField1;
    }

    public JTextField getjEndDateTextField() {
        return jEndDateTextField;
    }

    public void setjEndDateTextField(JTextField jEndDateTextField) {
        this.jEndDateTextField = jEndDateTextField;
    }

    public JTextField getjStartDateTextField() {
        return jStartDateTextField;
    }

    public void setjStartDateTextField(JTextField jStartDateTextField) {
        this.jStartDateTextField = jStartDateTextField;
    }
    
    public void clearInputs(){
        jNameTextField1.setText("");
        jStartDateTextField.setText("");
        jEndDateTextField.setText("");
        jSearchTextField.setText("");
    }
}
