/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.facens.upx2.smartgarden.view.form;

import com.facens.upx2.smartgarden.controller.LandsController;
import com.facens.upx2.smartgarden.controller.helper.LandsControllerHelper;
import com.facens.upx2.smartgarden.interfaces.AddressScreen;
import com.facens.upx2.smartgarden.model.helper.domain.ComboItem;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Gustavo Rosendo Cardoso
 */
public class LandsScreen extends javax.swing.JFrame implements AddressScreen {
        
    private LandsController landsController;
    private LandsControllerHelper landsControllerHelper;
    private Long institutionId;
        
    /**
     * Creates new form LandsScreen
     */
    public LandsScreen(long institutionId){
        setUndecorated(true); 
        initComponents();  
                
        setSize(1600, 754);
        setLocationRelativeTo(null);
        setResizable(false);
        
        this.landsControllerHelper = new LandsControllerHelper(this);
        this.landsController = new LandsController(landsControllerHelper, this);
        
        this.institutionId = institutionId;
        
        this.loadData(this.institutionId);
        
        BackgroundImage.setIcon( new javax.swing.ImageIcon( getClass().getResource("/com/facens/upx2/smartgarden/view/images/Lands.png") ) );
        
        jButtonBack.setOpaque(false);
        jButtonBack.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jButtonBack.setBorder(null); 
        
        jButtonRegister.setOpaque(false);
        jButtonRegister.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jButtonRegister.setBorder(null); 
        
        jSearchButton.setOpaque(false);
        jSearchButton.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jSearchButton.setBorder(null); 
        
        jDeleteButton.setOpaque(false);
        jDeleteButton.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jDeleteButton.setBorder(null); 
        
        jNameTextField1.setOpaque(false);
        jNameTextField1.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jNameTextField1.setBorder(null); 
        
        jCEPTextField.setOpaque(false);
        jCEPTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jCEPTextField.setBorder(null);
        
        jCountryComboBox.setOpaque(false);
        jCountryComboBox.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jCountryComboBox.setBorder(null);
        
        jStateComboBox.setOpaque(false);
        jStateComboBox.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jStateComboBox.setBorder(null);
        
        jCityComboBox.setOpaque(false);
        jCityComboBox.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jCityComboBox.setBorder(null);
        
        jNeighborhoodNameTextField.setOpaque(false);
        jNeighborhoodNameTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jNeighborhoodNameTextField.setBorder(null);
        
        jStreetTextField.setOpaque(false);
        jStreetTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jStreetTextField.setBorder(null);
        
        jNumberTextField.setOpaque(false);
        jNumberTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jNumberTextField.setBorder(null);
        
        jSearchTextField.setOpaque(false);
        jSearchTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jSearchTextField.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jNumberTextField = new javax.swing.JTextField();
        jCityComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jCountryComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jStateComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jCEPTextField = new javax.swing.JTextField();
        jNeighborhoodNameTextField = new javax.swing.JTextField();
        jStreetTextField = new javax.swing.JTextField();
        jNameTextField1 = new javax.swing.JTextField();
        jSearchTextField = new javax.swing.JTextField();
        jSearchButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 754));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 140, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CEP", "Cidade", "Bairro", "Rua", "Número", "Data"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 940, 210));

        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 40, 40));
        getContentPane().add(jNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 294, 290, 30));

        getContentPane().add(jCityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 224, 290, 30));

        jCountryComboBox.setAutoscrolls(true);
        jCountryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCountryComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jCountryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(934, 154, 290, 30));

        jStateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStateComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jStateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 224, 290, 30));
        getContentPane().add(jCEPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 154, 290, 30));
        getContentPane().add(jNeighborhoodNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(934, 224, 290, 30));
        getContentPane().add(jStreetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 294, 290, 30));
        getContentPane().add(jNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 154, 290, 30));
        getContentPane().add(jSearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 475, 830, 30));

        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1141, 477, 22, 24));

        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1169, 477, 22, 24));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/facens/upx2/smartgarden/view/images/Lands.png"))); // NOI18N
        getContentPane().add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 754));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        String landName = this.getjNameTextField1().getText();
        String landCep = this.getjCEPTextField().getText();
        String neighborhoodName = this.getjNeighborhoodNameTextField().getText();
        String streetName = this.getjStreetTextField().getText();
        String number = this.getjNumberTextField().getText().trim();
        Long cityId = 0L;
        
        Object selectedItem = jCityComboBox.getSelectedItem();
        
        if(selectedItem instanceof ComboItem comboItem){
            cityId = comboItem.getId();
        }
        
        this.landsController.registerLand(landName, landCep, neighborhoodName, streetName, number, cityId, this.institutionId);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jStateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStateComboBoxActionPerformed
        Object selectedItem = jStateComboBox.getSelectedItem(); 
        
        if(selectedItem instanceof ComboItem comboItem){ 
            long stateId = comboItem.getId(); 
            this.landsController.loadCitiesByStateId(stateId); 
        } 
    }//GEN-LAST:event_jStateComboBoxActionPerformed

    private void jCountryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCountryComboBoxActionPerformed
        Object selectedItem = jCountryComboBox.getSelectedItem();

        if(selectedItem instanceof ComboItem comboItem){
            long countryId = comboItem.getId();
            this.landsController.loadStatesByCountryId(countryId);
        }
    }//GEN-LAST:event_jCountryComboBoxActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        String search = this.getjSearchTextField().getText();
        
        this.loadDataWithSearch(this.institutionId, search);
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        landsController.deleteSelectedLand(this.institutionId);
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JTextField jCEPTextField;
    private javax.swing.JComboBox jCityComboBox;
    private javax.swing.JComboBox jCountryComboBox;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JTextField jNameTextField1;
    private javax.swing.JTextField jNeighborhoodNameTextField;
    private javax.swing.JTextField jNumberTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchTextField;
    private javax.swing.JComboBox jStateComboBox;
    private javax.swing.JTextField jStreetTextField;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void loadData(long institutionId){
        this.landsController.loadLands(institutionId);
        this.landsController.loadCountries();
    }
    
    private void loadDataWithSearch(long institutionId, String search){
        this.landsController.loadLandsWithSearch(institutionId, search);
    }

    public JTable getTableLands() {
        return jTable1;
    }

    public void setTableLands(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JComboBox<ComboItem> getjCountryComboBox() {
    return jCountryComboBox;
}

    public void setjCountryComboBox(JComboBox<ComboItem> jCountryComboBox) {
        this.jCountryComboBox = jCountryComboBox;
    }

    public JComboBox<ComboItem> getjStateComboBox() {
        return jStateComboBox;
    }

    public void setjStateComboBox(JComboBox<ComboItem> jStateComboBox) {
        this.jStateComboBox = jStateComboBox;
    } 

    public JComboBox<ComboItem> getjCityComboBox() {
        return jCityComboBox;
    }

    public void setjCityComboBox(JComboBox<ComboItem> jCityComboBox) {
        this.jCityComboBox = jCityComboBox;
    }

    public JTextField getjSearchTextField() {
        return jSearchTextField;
    }

    public void setjSearchTextField(JTextField jSearchTextField) {
        this.jSearchTextField = jSearchTextField;
    }

    public JTextField getjCEPTextField() {
        return jCEPTextField;
    }

    public void setjCEPTextField(JTextField jCEPTextField) {
        this.jCEPTextField = jCEPTextField;
    }

    public JTextField getjNameTextField1() {
        return jNameTextField1;
    }

    public void setjNameTextField1(JTextField jNameTextField1) {
        this.jNameTextField1 = jNameTextField1;
    }

    public JTextField getjNeighborhoodNameTextField() {
        return jNeighborhoodNameTextField;
    }

    public void setjNeighborhoodNameTextField(JTextField jNeighborhoodNameTextField) {
        this.jNeighborhoodNameTextField = jNeighborhoodNameTextField;
    }

    public JTextField getjNumberTextField() {
        return jNumberTextField;
    }

    public void setjNumberTextField(JTextField jNumberTextField) {
        this.jNumberTextField = jNumberTextField;
    }

    public JTextField getjStreetTextField() {
        return jStreetTextField;
    }

    public void setjStreetTextField(JTextField jStreetTextField) {
        this.jStreetTextField = jStreetTextField;
    }
    
    public void clearInputs(){
        jNameTextField1.setText("");
        jCEPTextField.setText("");
        jNeighborhoodNameTextField.setText("");
        jStreetTextField.setText("");
        jNumberTextField.setText("");
        jSearchTextField.setText("");

        jCountryComboBox.setSelectedIndex(0);
        jStateComboBox.removeAllItems();
        jStateComboBox.addItem(new ComboItem(0L, "Estado"));

        jCityComboBox.removeAllItems();
        jCityComboBox.addItem(new ComboItem(0L, "Cidade"));
    }
}
