/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.facens.upx2.smartgarden.view.form;

import com.facens.upx2.smartgarden.controller.LandsController;
import com.facens.upx2.smartgarden.controller.helper.LandsControllerHelper;
import com.facens.upx2.smartgarden.model.domain.Cities;
import com.facens.upx2.smartgarden.model.domain.Countries;
import com.facens.upx2.smartgarden.model.domain.Lands;
import com.facens.upx2.smartgarden.model.domain.States;
import com.facens.upx2.smartgarden.model.helper.domain.ComboItem;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Gustavo Rosendo Cardoso
 */
public class LandsScreen extends javax.swing.JFrame {
        
    private LandsController landsController;
    private LandsControllerHelper landsControllerHelper;
    private Long institutionId;
        
    /**
     * Creates new form LandsScreen
     */
    public LandsScreen(long institutionId){
        setUndecorated(true); 
        initComponents();  
                
        setSize(1600, 754);
        setLocationRelativeTo(null);
        setResizable(false);
        
        this.landsControllerHelper = new LandsControllerHelper(this);
        this.landsController = new LandsController(landsControllerHelper, this);
        
        this.institutionId = institutionId;
        
        this.loadData(this.institutionId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jNumberTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCityComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jCountryComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jLabel3 = new javax.swing.JLabel();
        jStateComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jLabel4 = new javax.swing.JLabel();
        jCEPTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jNeighborhoodNameTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jStreetTextField = new javax.swing.JTextField();
        jNameTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSearchTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSearchButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 754));
        setPreferredSize(new java.awt.Dimension(1600, 754));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegister.setText("Cadastrar Terreno");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Cidade", "CEP", "Bairro", "Rua", "Numero", "Data"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 1580, 340));

        jButtonBack.setText("Voltar");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setText("Numero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 70, -1, -1));
        getContentPane().add(jNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 90, 170, -1));

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jCityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma cidade" }));
        getContentPane().add(jCityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 190, -1));

        jCountryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um País" }));
        jCountryComboBox.setAutoscrolls(true);
        jCountryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCountryComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jCountryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 120, -1));

        jLabel3.setText("País");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jStateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um estado" }));
        jStateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStateComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jStateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 190, -1));

        jLabel4.setText("Estado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));
        getContentPane().add(jCEPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 170, -1));

        jLabel5.setText("CEP");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel6.setText("Bairro");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 70, -1, -1));
        getContentPane().add(jNeighborhoodNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 90, 170, -1));

        jLabel8.setText("Rua");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 70, -1, -1));
        getContentPane().add(jStreetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 90, 170, -1));
        getContentPane().add(jNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, -1));

        jLabel7.setText("Cidade");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, -1, -1));
        getContentPane().add(jSearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 170, -1));

        jLabel9.setText("Pesquisar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jSearchButton.setText("Buscar");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jDeleteButton.setText("Excluir Terreno Selecionado");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        String landName = this.getjNameTextField1().getText();
        String landCep = this.getjCEPTextField().getText();
        String neighborhoodName = this.getjNeighborhoodNameTextField().getText();
        String streetName = this.getjStreetTextField().getText();
        String number = this.getjNumberTextField().getText().trim();
        Long cityId = 0L;
        
        Object selectedItem = jCityComboBox.getSelectedItem();
        
        if(selectedItem instanceof ComboItem comboItem){
            cityId = comboItem.getId();
        }
        
        this.landsController.registerLand(landName, landCep, neighborhoodName, streetName, number, cityId, this.institutionId);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jStateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStateComboBoxActionPerformed
        Object selectedItem = jStateComboBox.getSelectedItem(); 
        
        if(selectedItem instanceof ComboItem comboItem){ 
            long stateId = comboItem.getId(); 
            this.landsController.loadCitiesByStateId(stateId); 
        } 
    }//GEN-LAST:event_jStateComboBoxActionPerformed

    private void jCountryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCountryComboBoxActionPerformed
        Object selectedItem = jCountryComboBox.getSelectedItem();

        if(selectedItem instanceof ComboItem comboItem){
            long countryId = comboItem.getId();
            this.landsController.loadStatesByCountryId(countryId);
        }
    }//GEN-LAST:event_jCountryComboBoxActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        String search = this.getjSearchTextField().getText();
        
        this.loadDataWithSearch(this.institutionId, search);
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        landsController.deleteSelectedLand(this.institutionId);
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JTextField jCEPTextField;
    private javax.swing.JComboBox jCityComboBox;
    private javax.swing.JComboBox jCountryComboBox;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNameTextField1;
    private javax.swing.JTextField jNeighborhoodNameTextField;
    private javax.swing.JTextField jNumberTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchTextField;
    private javax.swing.JComboBox jStateComboBox;
    private javax.swing.JTextField jStreetTextField;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void loadData(long institutionId){
        this.landsController.loadLands(institutionId);
        this.landsController.loadCountries();
    }
    
    private void loadDataWithSearch(long institutionId, String search){
        this.landsController.loadLands(institutionId);
        
        this.landsController.loadLandsWithSearch(institutionId, search);
    }

    public JTable getTableLands() {
        return jTable1;
    }

    public void setTableLands(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JComboBox<ComboItem> getjCountryComboBox() {
    return jCountryComboBox;
}

    public void setjCountryComboBox(JComboBox<ComboItem> jCountryComboBox) {
        this.jCountryComboBox = jCountryComboBox;
    }

    public JComboBox<ComboItem> getjStateComboBox() {
        return jStateComboBox;
    }

    public void setjStateComboBox(JComboBox<ComboItem> jStateComboBox) {
        this.jStateComboBox = jStateComboBox;
    } 

    public JComboBox<ComboItem> getjCityComboBox() {
        return jCityComboBox;
    }

    public void setjCityComboBox(JComboBox<ComboItem> jCityComboBox) {
        this.jCityComboBox = jCityComboBox;
    }

    public JTextField getjSearchTextField() {
        return jSearchTextField;
    }

    public void setjSearchTextField(JTextField jSearchTextField) {
        this.jSearchTextField = jSearchTextField;
    }

    public JTextField getjCEPTextField() {
        return jCEPTextField;
    }

    public void setjCEPTextField(JTextField jCEPTextField) {
        this.jCEPTextField = jCEPTextField;
    }

    public JTextField getjNameTextField1() {
        return jNameTextField1;
    }

    public void setjNameTextField1(JTextField jNameTextField1) {
        this.jNameTextField1 = jNameTextField1;
    }

    public JTextField getjNeighborhoodNameTextField() {
        return jNeighborhoodNameTextField;
    }

    public void setjNeighborhoodNameTextField(JTextField jNeighborhoodNameTextField) {
        this.jNeighborhoodNameTextField = jNeighborhoodNameTextField;
    }

    public JTextField getjNumberTextField() {
        return jNumberTextField;
    }

    public void setjNumberTextField(JTextField jNumberTextField) {
        this.jNumberTextField = jNumberTextField;
    }

    public JTextField getjStreetTextField() {
        return jStreetTextField;
    }

    public void setjStreetTextField(JTextField jStreetTextField) {
        this.jStreetTextField = jStreetTextField;
    }
    
    public void clearInputs(){
        jNameTextField1.setText("");
        jCEPTextField.setText("");
        jNeighborhoodNameTextField.setText("");
        jStreetTextField.setText("");
        jNumberTextField.setText("");
        jSearchTextField.setText("");

        jCountryComboBox.setSelectedIndex(0);
        jStateComboBox.removeAllItems();
        jStateComboBox.addItem(new ComboItem(0L, "Estado"));

        jCityComboBox.removeAllItems();
        jCityComboBox.addItem(new ComboItem(0L, "Cidade"));
    }
}
