/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.facens.upx2.smartgarden.view.form;

import com.facens.upx2.smartgarden.controller.LoginController;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Gustavo Rosendo Cardoso
 */
public class LoginScreen extends javax.swing.JFrame{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginScreen.class.getName());
    
    private LoginController loginController;

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen(){ 
        setUndecorated(true); 
        initComponents(); 
        
        BackgroundImage.setIcon( new javax.swing.ImageIcon( getClass().getResource("/com/facens/upx2/smartgarden/view/images/Login.png") ) );
        
        setSize(1600, 754);
        setLocationRelativeTo(null);
        setResizable(false);
        
        this.loginController = new LoginController(this); 
        
        LoginText.setOpaque(false);
        LoginText.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        LoginText.setBorder(null); 
        
        PasswordText.setOpaque(false);
        PasswordText.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        PasswordText.setBorder(null); 
        
        LoginButton.setOpaque(false);
        LoginButton.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        LoginButton.setBorder(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginText = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        PasswordText = new javax.swing.JPasswordField();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginText.setBackground(new java.awt.Color(0, 0, 0));
        LoginText.setActionCommand("<Not Set>");
        LoginText.setAutoscrolls(false);
        LoginText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginText.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(LoginText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 345, 410, 40));

        LoginButton.setBackground(new java.awt.Color(0, 0, 0));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 493, 420, 45));

        PasswordText.setBackground(new java.awt.Color(0, 0, 0));
        PasswordText.setBorder(null);
        getContentPane().add(PasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 436, 410, 40));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/facens/upx2/smartgarden/view/images/Login.png"))); // NOI18N
        getContentPane().add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 754));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonButtonActionPerformed
        this.loginController.login();
    }//GEN-LAST:event_LoginButtonButtonActionPerformed

    public JTextField getTxtLogin(){
        return LoginText;
    }
    
    public JTextField getTxtPassword(){
        return PasswordText;
    }
    
    public JButton getLoginButton(){
        return LoginButton;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField LoginText;
    private javax.swing.JPasswordField PasswordText;
    // End of variables declaration//GEN-END:variables
}
