/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.facens.upx2.smartgarden.view.form;

import com.facens.upx2.smartgarden.controller.MainMenuController;
import com.facens.upx2.smartgarden.model.domain.Users;

/**
 *
 * @author gusta
 */
public class MainMenuScreen extends javax.swing.JFrame{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuScreen.class.getName());
    
    private final MainMenuController mainMenuController;
    private final Users users;

    /**
     * Creates new form MainMenuScreen
    */
    public MainMenuScreen(Users users){
        setUndecorated(true); 
        initComponents(); 
        
        this.users = users;
        this.mainMenuController = new MainMenuController(this, users);
                
        setSize(1600, 754);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 754));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Cadastrar Horta");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jButton2.setText("Cadastrar Colheita");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jButton3.setText("Cadastrar Usuario");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jButton4.setText("Cadastrar Terreno");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigateToLandsScreen(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jButton5.setText("Cadastrar Voluntario");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navigateToLandsScreen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigateToLandsScreen
        // TODO add your handling code here:
        this.mainMenuController.navigateToLandsScreen();
    }//GEN-LAST:event_navigateToLandsScreen

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
