/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.facens.upx2.smartgarden.view.form;

import com.facens.upx2.smartgarden.controller.MainMenuController;
import com.facens.upx2.smartgarden.model.domain.Users;

/**
 *
 * @author gusta
 */
public class MainMenuScreen extends javax.swing.JFrame{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuScreen.class.getName());
    
    private final MainMenuController mainMenuController;
    private final Users users;

    /**
     * Creates new form MainMenuScreen
    */
    public MainMenuScreen(Users users){
        setUndecorated(true); 
        initComponents(); 
        
        this.users = users;
        this.mainMenuController = new MainMenuController(users);
                
        setSize(1600, 754);
        setLocationRelativeTo(null);
        setResizable(false);
        
        BackgroundImage.setIcon( new javax.swing.ImageIcon( getClass().getResource("/com/facens/upx2/smartgarden/view/images/Home.png") ) );
        
        jButton1.setOpaque(false);
        jButton1.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jButton1.setBorder(null); 
        
        jButton3.setOpaque(false);
        jButton3.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jButton3.setBorder(null); 
        
        jButton4.setOpaque(false);
        jButton4.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jButton4.setBorder(null); 
        
        jButton5.setOpaque(false);
        jButton5.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jButton5.setBorder(null); 
        
        jButton6.setOpaque(false);
        jButton6.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jButton6.setBorder(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, 310, 180));

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 310, 190));

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigateToLandsScreen(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 310, 180));

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 310, 180));

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 380, 310, 190));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/facens/upx2/smartgarden/view/images/Home.png"))); // NOI18N
        getContentPane().add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 754));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navigateToLandsScreen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigateToLandsScreen
        // TODO add your handling code here:
        this.mainMenuController.navigateToLandsScreen();
    }//GEN-LAST:event_navigateToLandsScreen

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.mainMenuController.navigateToPlantingsScreen();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.mainMenuController.navigateToCropTypesScreen();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.mainMenuController.navigateToVolunteersScreen();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.mainMenuController.navigateToUsersScreen();
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    // End of variables declaration//GEN-END:variables
}
