/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.facens.upx2.smartgarden.view.form;

import com.facens.upx2.smartgarden.controller.PlantingsController;
import com.facens.upx2.smartgarden.controller.helper.PlantingsControllerHelper;
import com.facens.upx2.smartgarden.model.helper.domain.ComboItem;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Gustavo Rosendo Cardoso
 */
public class PlantingsScreen extends javax.swing.JFrame {
    
    private PlantingsController plantingsController;
    private PlantingsControllerHelper plantingsControllerHelper;
    private Long institutionId;
        
    /**
     * Creates new form UserScreen
     */
    public PlantingsScreen(long institutionId){
        setUndecorated(true); 
        initComponents();  
                
        setSize(1600, 754);
        setLocationRelativeTo(null);
        setResizable(false);
        
        this.plantingsControllerHelper = new PlantingsControllerHelper(this);
        this.plantingsController = new PlantingsController(plantingsControllerHelper, this);
        
        this.institutionId = institutionId;
        
        this.loadData(this.institutionId);
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PlantingsScreen.class.getName());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdvance = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        jSearchButton = new javax.swing.JButton();
        jApproximatedHarvestDateTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSearchTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxActions = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButtonBack1 = new javax.swing.JButton();
        jComboBoxLands = new javax.swing.JComboBox<ComboItem>() ;
        jLabel12 = new javax.swing.JLabel();
        jCropTypeComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAdvance.setText("Avancar");
        jButtonAdvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdvanceActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdvance, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, -1, -1));

        jButtonRegister.setText("Cadastrar Horta");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        jSearchButton.setText("Buscar");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));
        getContentPane().add(jApproximatedHarvestDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Terreno", "Total Voluntario", "Total Custos (R$)", "Total Producao (R$)", "Total Producao (KG)", "Data Aproxima da Colheita", "Lucro Final", "Data"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 1580, 340));
        getContentPane().add(jSearchTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 170, -1));

        jLabel10.setText("Pesquisar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jComboBoxActions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ação", "Adicionar Voluntario", "Adicionar Custos", "Adicionar Producoes", "Finalizar Producao", "Deletar Horta" }));
        jComboBoxActions.setToolTipText("");
        getContentPane().add(jComboBoxActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        jLabel11.setText("Terreno");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jButtonBack1.setText("Voltar");
        jButtonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jComboBoxLands.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um terreno" }));
        getContentPane().add(jComboBoxLands, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel12.setText("Data Aproximada da Colheita");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jCropTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um tipo de plantio" }));
        getContentPane().add(jCropTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel13.setText("Tipo Plantio");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdvanceActionPerformed
        String action = (String) jComboBoxActions.getSelectedItem();

        if(action == null){
            return;
        } 
    
        switch(action){
            case "Adicionar Voluntario":
                System.out.println(action);
                break;

            case "Adicionar Custos":
                System.out.println(action);
                break;

            case "Adicionar Producoes":
                System.out.println(action);
                break;

            case "Finalizar Producao":
                System.out.println(action);;
                break;

            case "Deletar Horta":
                System.out.println(action);
                break;

            default:
                break;
        }
    }//GEN-LAST:event_jButtonAdvanceActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        String approximatedHarvestDate = this.getjApproximatedHarvestDateTextField().getText();
        
        Long landId = 0L;

        Object selectedItem = jComboBoxLands.getSelectedItem();

        if(selectedItem instanceof ComboItem comboItem){
            landId = comboItem.getId();
        }
        
        Long cropTypeId = 0L;

        Object selectedItem2 = jCropTypeComboBox.getSelectedItem();

        if(selectedItem2 instanceof ComboItem comboItem){
            cropTypeId = comboItem.getId();
        }

        this.plantingsController.registerPlanting(approximatedHarvestDate, landId, cropTypeId, this.institutionId);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
       String search = this.getjSearchTextField1().getText();

       this.loadDataWithSearch(this.institutionId, search);
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jButtonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonBack1ActionPerformed

    private void loadData(long institutionId){
        this.plantingsController.loadPlantings(institutionId);
        this.plantingsController.loadCropTypes(institutionId);
        this.plantingsController.loadLands(institutionId);
    }
    
    private void loadDataWithSearch(long institutionId, String search){
        this.plantingsController.loadPlantingsWithSearch(institutionId, search);
    }

    public JTextField getjApproximatedHarvestDateTextField() {
        return jApproximatedHarvestDateTextField;
    }

    public void setjApproximatedHarvestDateTextField(JTextField jApproximatedHarvestDateTextField) {
        this.jApproximatedHarvestDateTextField = jApproximatedHarvestDateTextField;
    }

    public JButton getjButtonAdvance() {
        return jButtonAdvance;
    }

    public void setjButtonAdvance(JButton jButtonAdvance) {
        this.jButtonAdvance = jButtonAdvance;
    }

    public JButton getjButtonBack1() {
        return jButtonBack1;
    }

    public void setjButtonBack1(JButton jButtonBack1) {
        this.jButtonBack1 = jButtonBack1;
    }

    public JButton getjButtonRegister() {
        return jButtonRegister;
    }

    public void setjButtonRegister(JButton jButtonRegister) {
        this.jButtonRegister = jButtonRegister;
    }

    public JButton getjSearchButton() {
        return jSearchButton;
    }

    public void setjSearchButton(JButton jSearchButton) {
        this.jSearchButton = jSearchButton;
    }

    public JComboBox<String> getjComboBoxActions() {
        return jComboBoxActions;
    }

    public void setjComboBoxActions(JComboBox<String> jComboBoxActions) {
        this.jComboBoxActions = jComboBoxActions;
    }

    public JComboBox<ComboItem> getjComboBoxLands(){
        return jComboBoxLands;
    }

    public void setjComboBoxLands(JComboBox<ComboItem> jComboBoxLands){
        this.jComboBoxLands = jComboBoxLands;
    }

    public JComboBox<ComboItem> getjCropTypeComboBox() {
        return jCropTypeComboBox;
    }

    public void setjCropTypeComboBox(JComboBox<ComboItem> jCropTypeComboBox) {
        this.jCropTypeComboBox = jCropTypeComboBox;
    }

    public JTextField getjSearchTextField1() {
        return jSearchTextField1;
    }

    public void setjSearchTextField1(JTextField jSearchTextField1) {
        this.jSearchTextField1 = jSearchTextField1;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jApproximatedHarvestDateTextField;
    private javax.swing.JButton jButtonAdvance;
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JComboBox<String> jComboBoxActions;
    private javax.swing.JComboBox jComboBoxLands;
    private javax.swing.JComboBox jCropTypeComboBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchTextField1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
