/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.facens.upx2.smartgarden.view.form;

import com.facens.upx2.smartgarden.controller.VolunteerPlantingsController;
import com.facens.upx2.smartgarden.controller.helper.VolunteerPlantingsControllerHelper;
import com.facens.upx2.smartgarden.interfaces.AddressScreen;
import com.facens.upx2.smartgarden.model.helper.domain.ComboItem;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Gustavo Rosendo Cardoso
 */
public class PlantingVolunteerScreen extends javax.swing.JFrame {
        
    private VolunteerPlantingsController volunteerPlantingsController;
    private VolunteerPlantingsControllerHelper volunteerPlantingsControllerHelper;
    private Long institutionId;
    private Long plantingId;
        
    /**
     * Creates new form CropTypesScreen
     */
    public PlantingVolunteerScreen(long institutionId, long plantingId){
        setUndecorated(true); 
        initComponents();  
                
        setSize(1600, 754);
        setLocationRelativeTo(null);
        setResizable(false);
        
        this.volunteerPlantingsControllerHelper = new VolunteerPlantingsControllerHelper(this);
        this.volunteerPlantingsController = new VolunteerPlantingsController(volunteerPlantingsControllerHelper, this);
        
        this.institutionId = institutionId;
        
        this.loadData(this.institutionId, this.plantingId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jSearchTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSearchButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jComboBoxVolunteers = new javax.swing.JComboBox<ComboItem>() ;
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 754));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegister.setText("Adicionar Voluntário");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Completo", "Email", "CEP", "Cidade", "Bairro", "Rua", "Numero", "Data"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 1580, 340));

        jButtonBack.setText("Voltar");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        getContentPane().add(jSearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 170, -1));

        jLabel9.setText("Pesquisar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jSearchButton.setText("Buscar");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jDeleteButton.setText("Excluir Voluntário Selecionado");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, -1, -1));

        jComboBoxVolunteers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um voluntário" }));
        getContentPane().add(jComboBoxVolunteers, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel11.setText("Voluntário");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        Long volunteerId = 0L;

        Object selectedItem = jComboBoxVolunteers.getSelectedItem();

        if(selectedItem instanceof ComboItem comboItem){
            volunteerId = comboItem.getId();
        }
        
        this.volunteerPlantingsController.registerVolunteer(volunteerId, this.institutionId);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        String search = this.getjSearchTextField().getText();
        
        this.loadDataWithSearch(this.institutionId, search);
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        volunteerPlantingsController.deleteSelectedVolunteer(this.institutionId, this.plantingId);
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JComboBox jComboBoxVolunteers;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchTextField;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void loadData(Long institutionId, Long plantingId){
        this.volunteerPlantingsController.loadVolunteers(institutionId, plantingId);
        this.volunteerPlantingsController.loadVolunteersForComboBox(institutionId);
    }
    
    private void loadDataWithSearch(Long institutionId, String search){
        this.volunteerPlantingsController.loadVolunteersWithSearch(institutionId, search, this.plantingId);
    }

    public JButton getjButtonBack() {
        return jButtonBack;
    }

    public void setjButtonBack(JButton jButtonBack) {
        this.jButtonBack = jButtonBack;
    }

    public JButton getjButtonRegister() {
        return jButtonRegister;
    }

    public void setjButtonRegister(JButton jButtonRegister) {
        this.jButtonRegister = jButtonRegister;
    }

    public JComboBox<ComboItem> getjComboBoxVolunteers() {
        return jComboBoxVolunteers;
    }

    public void setjComboBoxVolunteers(JComboBox<ComboItem> jComboBoxVolunteers) {
        this.jComboBoxVolunteers = jComboBoxVolunteers;
    }

    public JButton getjDeleteButton() {
        return jDeleteButton;
    }

    public void setjDeleteButton(JButton jDeleteButton) {
        this.jDeleteButton = jDeleteButton;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JButton getjSearchButton() {
        return jSearchButton;
    }

    public void setjSearchButton(JButton jSearchButton) {
        this.jSearchButton = jSearchButton;
    }

    public JTextField getjSearchTextField() {
        return jSearchTextField;
    }

    public void setjSearchTextField(JTextField jSearchTextField) {
        this.jSearchTextField = jSearchTextField;
    }
    
    public void clearInputs(){
    }
}
