/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.facens.upx2.smartgarden.view.form;

import com.facens.upx2.smartgarden.controller.VolunteerPlantingsController;
import com.facens.upx2.smartgarden.controller.helper.VolunteerPlantingsControllerHelper;
import com.facens.upx2.smartgarden.interfaces.AddressScreen;
import com.facens.upx2.smartgarden.model.helper.domain.ComboItem;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Gustavo Rosendo Cardoso
 */
public class PlantingVolunteerScreen extends javax.swing.JFrame implements AddressScreen {
        
    private VolunteerPlantingsController registerVolunteerController;
    private VolunteerPlantingsControllerHelper registerVolunteerControllerHelper;
    private Long institutionId;
        
    /**
     * Creates new form CropTypesScreen
     */
    public PlantingVolunteerScreen(long institutionId){
        setUndecorated(true); 
        initComponents();  
                
        setSize(1600, 754);
        setLocationRelativeTo(null);
        setResizable(false);
        
        this.registerVolunteerControllerHelper = new VolunteerPlantingsControllerHelper(this);
        this.registerVolunteerController = new VolunteerPlantingsController(registerVolunteerControllerHelper, this);
        
        this.institutionId = institutionId;
        
        this.loadData(this.institutionId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jSearchTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSearchButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jCEPTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCountryComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jLabel3 = new javax.swing.JLabel();
        jStateComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jLabel4 = new javax.swing.JLabel();
        jCityComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jLabel7 = new javax.swing.JLabel();
        jNeighborhoodNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jStreetTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jNumberTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFullNameTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jEmailTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 754));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegister.setText("Cadastrar Voluntário");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Completo", "Email", "CEP", "Cidade", "Bairro", "Rua", "Numero", "Data"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 1580, 340));

        jButtonBack.setText("Voltar");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        getContentPane().add(jSearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 170, -1));

        jLabel9.setText("Pesquisar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jSearchButton.setText("Buscar");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jDeleteButton.setText("Excluir Voluntário Selecionado");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, -1, -1));
        getContentPane().add(jCEPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 170, -1));

        jLabel5.setText("CEP");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jCountryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um País" }));
        jCountryComboBox.setAutoscrolls(true);
        jCountryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCountryComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jCountryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 120, -1));

        jLabel3.setText("País");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jStateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um estado" }));
        jStateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStateComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jStateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 190, -1));

        jLabel4.setText("Estado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        jCityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma cidade" }));
        getContentPane().add(jCityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 190, -1));

        jLabel7.setText("Cidade");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, -1));
        getContentPane().add(jNeighborhoodNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 90, 170, -1));

        jLabel6.setText("Bairro");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 70, -1, -1));
        getContentPane().add(jStreetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 90, 170, -1));

        jLabel8.setText("Rua");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 70, -1, -1));
        getContentPane().add(jNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 90, 170, -1));

        jLabel1.setText("Numero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 70, -1, -1));

        jLabel10.setText("Nome Completo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        getContentPane().add(jFullNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, -1));

        jLabel11.setText("Email");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        getContentPane().add(jEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        String name = this.getjFullNameTextField().getText();
        String email = this.getjEmailTextField().getText();
        String userCep = this.getjCEPTextField().getText();
        String neighborhoodName = this.getjNeighborhoodNameTextField().getText();
        String streetName = this.getjStreetTextField().getText();
        String number = this.getjNumberTextField().getText().trim();
        Long cityId = 0L;
        
        Object selectedItem = jCityComboBox.getSelectedItem();
        
        if(selectedItem instanceof ComboItem comboItem){
            cityId = comboItem.getId();
        }
        
        this.registerVolunteerController.registerVolunteer(name, email, userCep, neighborhoodName, streetName, number, cityId, this.institutionId);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        String search = this.getjSearchTextField().getText();
        
        this.loadDataWithSearch(this.institutionId, search);
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        registerVolunteerController.deleteSelectedCropType(this.institutionId);
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jCountryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCountryComboBoxActionPerformed
        Object selectedItem = jCountryComboBox.getSelectedItem();

        if(selectedItem instanceof ComboItem comboItem){
            long countryId = comboItem.getId();
            this.registerVolunteerController.loadStatesByCountryId(countryId);
        }
    }//GEN-LAST:event_jCountryComboBoxActionPerformed

    private void jStateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStateComboBoxActionPerformed
        Object selectedItem = jStateComboBox.getSelectedItem();

        if(selectedItem instanceof ComboItem comboItem){
            long stateId = comboItem.getId();
            this.registerVolunteerController.loadCitiesByStateId(stateId);
        }
    }//GEN-LAST:event_jStateComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JTextField jCEPTextField;
    private javax.swing.JComboBox jCityComboBox;
    private javax.swing.JComboBox jCountryComboBox;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JTextField jEmailTextField;
    private javax.swing.JTextField jFullNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNeighborhoodNameTextField;
    private javax.swing.JTextField jNumberTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchTextField;
    private javax.swing.JComboBox jStateComboBox;
    private javax.swing.JTextField jStreetTextField;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void loadData(long institutionId){
        this.registerVolunteerController.loadVolunteers(institutionId);
    }
    
    private void loadDataWithSearch(long institutionId, String search){
        this.registerVolunteerController.loadVolunteersWithSearch(institutionId, search);
    }

    public JButton getjButtonBack() {
        return jButtonBack;
    }

    public void setjButtonBack(JButton jButtonBack) {
        this.jButtonBack = jButtonBack;
    }

    public JButton getjButtonRegister() {
        return jButtonRegister;
    }

    public void setjButtonRegister(JButton jButtonRegister) {
        this.jButtonRegister = jButtonRegister;
    }

    public JTextField getjCEPTextField() {
        return jCEPTextField;
    }

    public void setjCEPTextField(JTextField jCEPTextField) {
        this.jCEPTextField = jCEPTextField;
    }

    public JComboBox getjCityComboBox() {
        return jCityComboBox;
    }

    public void setjCityComboBox(JComboBox jCityComboBox) {
        this.jCityComboBox = jCityComboBox;
    }

    public JComboBox getjCountryComboBox() {
        return jCountryComboBox;
    }

    public void setjCountryComboBox(JComboBox jCountryComboBox) {
        this.jCountryComboBox = jCountryComboBox;
    }

    public JButton getjDeleteButton() {
        return jDeleteButton;
    }

    public void setjDeleteButton(JButton jDeleteButton) {
        this.jDeleteButton = jDeleteButton;
    }

    public JTextField getjEmailTextField() {
        return jEmailTextField;
    }

    public void setjEmailTextField(JTextField jEmailTextField) {
        this.jEmailTextField = jEmailTextField;
    }

    public JTextField getjFullNameTextField() {
        return jFullNameTextField;
    }

    public void setjFullNameTextField(JTextField jFullNameTextField) {
        this.jFullNameTextField = jFullNameTextField;
    }

    public JTextField getjNeighborhoodNameTextField() {
        return jNeighborhoodNameTextField;
    }

    public void setjNeighborhoodNameTextField(JTextField jNeighborhoodNameTextField) {
        this.jNeighborhoodNameTextField = jNeighborhoodNameTextField;
    }

    public JTextField getjNumberTextField() {
        return jNumberTextField;
    }

    public void setjNumberTextField(JTextField jNumberTextField) {
        this.jNumberTextField = jNumberTextField;
    }

    public JButton getjSearchButton() {
        return jSearchButton;
    }

    public void setjSearchButton(JButton jSearchButton) {
        this.jSearchButton = jSearchButton;
    }

    public JTextField getjSearchTextField() {
        return jSearchTextField;
    }

    public void setjSearchTextField(JTextField jSearchTextField) {
        this.jSearchTextField = jSearchTextField;
    }

    public JComboBox getjStateComboBox() {
        return jStateComboBox;
    }

    public void setjStateComboBox(JComboBox jStateComboBox) {
        this.jStateComboBox = jStateComboBox;
    }

    public JTextField getjStreetTextField() {
        return jStreetTextField;
    }

    public void setjStreetTextField(JTextField jStreetTextField) {
        this.jStreetTextField = jStreetTextField;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }
    
    
    
    public void clearInputs(){
    }
}
