/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.facens.upx2.smartgarden.view.form;

import com.facens.upx2.smartgarden.controller.UsersController;
import com.facens.upx2.smartgarden.controller.helper.UsersControllerHelper;
import com.facens.upx2.smartgarden.interfaces.AddressScreen;
import com.facens.upx2.smartgarden.model.helper.domain.ComboItem;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Gustavo Rosendo Cardoso
 */
public class UsersScreen extends javax.swing.JFrame implements AddressScreen {
    
    private UsersController usersController;
    private UsersControllerHelper usersControllerHelper;
    private Long institutionId;
        
    /**
     * Creates new form UserScreen
     */
    public UsersScreen(long institutionId){
        setUndecorated(true); 
        initComponents();  
                
        setSize(1600, 754);
        setLocationRelativeTo(null);
        setResizable(false);
        
        this.usersControllerHelper = new UsersControllerHelper(this);
        this.usersController = new UsersController(usersControllerHelper, this);
        
        this.institutionId = institutionId;
        
        this.loadData(this.institutionId);
        
        BackgroundImage.setIcon( new javax.swing.ImageIcon( getClass().getResource("/com/facens/upx2/smartgarden/view/images/Users.png") ) );
        
        jButtonBack.setOpaque(false);
        jButtonBack.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jButtonBack.setBorder(null); 
        
        jButtonRegister.setOpaque(false);
        jButtonRegister.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jButtonRegister.setBorder(null); 
        
        jSearchButton.setOpaque(false);
        jSearchButton.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jSearchButton.setBorder(null); 
        
        jDeleteButton.setOpaque(false);
        jDeleteButton.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jDeleteButton.setBorder(null); 
        
        jUserNameTextField.setOpaque(false);
        jUserNameTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jUserNameTextField.setBorder(null); 
        
        jCEPTextField.setOpaque(false);
        jCEPTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jCEPTextField.setBorder(null);
        
        jCountryComboBox.setOpaque(false);
        jCountryComboBox.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jCountryComboBox.setBorder(null);
        
        jStateComboBox.setOpaque(false);
        jStateComboBox.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jStateComboBox.setBorder(null);
        
        jCityComboBox.setOpaque(false);
        jCityComboBox.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jCityComboBox.setBorder(null);
        
        jNeighborhoodNameTextField.setOpaque(false);
        jNeighborhoodNameTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jNeighborhoodNameTextField.setBorder(null);
        
        jStreetTextField.setOpaque(false);
        jStreetTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jStreetTextField.setBorder(null);
        
        jNumberTextField.setOpaque(false);
        jNumberTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jNumberTextField.setBorder(null);
        
        jSearchTextField.setOpaque(false);
        jSearchTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jSearchTextField.setBorder(null);
        
        jPasswordTextField.setOpaque(false);
        jPasswordTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jPasswordTextField.setBorder(null);
        
        jRepeatedPasswordTextField.setOpaque(false);
        jRepeatedPasswordTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jRepeatedPasswordTextField.setBorder(null);
        
        jEmailTextField.setOpaque(false);
        jEmailTextField.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jEmailTextField.setBorder(null);
        
        jNameTextField2.setOpaque(false);
        jNameTextField2.setBackground(new java.awt.Color(0, 0, 0, 0)); 
        jNameTextField2.setBorder(null);
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UsersScreen.class.getName());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jUserNameTextField = new javax.swing.JTextField();
        jCEPTextField = new javax.swing.JTextField();
        jCountryComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jStateComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jCityComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jNeighborhoodNameTextField = new javax.swing.JTextField();
        jStreetTextField = new javax.swing.JTextField();
        jNumberTextField = new javax.swing.JTextField();
        jEmailTextField = new javax.swing.JTextField();
        jNameTextField2 = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jSearchButton = new javax.swing.JButton();
        jSearchTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPasswordTextField = new javax.swing.JTextField();
        jRepeatedPasswordTextField = new javax.swing.JTextField();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 40, 40));
        getContentPane().add(jUserNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 148, 290, 30));
        getContentPane().add(jCEPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 148, 290, 30));

        jCountryComboBox.setAutoscrolls(true);
        jCountryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCountryComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jCountryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 148, 290, 30));

        jStateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStateComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jStateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 218, 290, 30));

        getContentPane().add(jCityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 218, 290, 30));
        getContentPane().add(jNeighborhoodNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 218, 290, 30));
        getContentPane().add(jStreetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 288, 290, 30));
        getContentPane().add(jNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 288, 290, 30));
        getContentPane().add(jEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 359, 290, 30));
        getContentPane().add(jNameTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 288, 290, 30));

        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 409, 130, 32));

        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 542, 25, 27));

        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1133, 542, 23, 27));
        getContentPane().add(jSearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 540, 828, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Email", "Nome Usr.", "Nome Cmp.", "CEP", "Cidade", "Bairro", "Rua", "Número", "Data"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 930, 160));
        getContentPane().add(jPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 290, 30));
        getContentPane().add(jRepeatedPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 290, 30));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/facens/upx2/smartgarden/view/images/Users.png"))); // NOI18N
        getContentPane().add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 754));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jCountryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCountryComboBoxActionPerformed
        Object selectedItem = jCountryComboBox.getSelectedItem();

        if(selectedItem instanceof ComboItem comboItem){
            long countryId = comboItem.getId();
            this.usersController.loadStatesByCountryId(countryId);
        }
    }//GEN-LAST:event_jCountryComboBoxActionPerformed

    private void jStateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStateComboBoxActionPerformed
        Object selectedItem = jStateComboBox.getSelectedItem();

        if(selectedItem instanceof ComboItem comboItem){
            long stateId = comboItem.getId();
            this.usersController.loadCitiesByStateId(stateId);
        }
    }//GEN-LAST:event_jStateComboBoxActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        String name = this.getjNameTextField2().getText();
        String email = this.getjEmailTextField().getText();
        String userName = this.getjUserNameTextField().getText();
        String password = this.getjPasswordTextField().getText();
        String repeatedPassword = this.getjRepeatedPasswordTextField().getText();
        String userCep = this.getjCEPTextField().getText();
        String neighborhoodName = this.getjNeighborhoodNameTextField().getText();
        String streetName = this.getjStreetTextField().getText();
        String number = this.getjNumberTextField().getText().trim();
        Long cityId = 0L;

        Object selectedItem = jCityComboBox.getSelectedItem();

        if(selectedItem instanceof ComboItem comboItem){
            cityId = comboItem.getId();
        }

        this.usersController.registerUser(name, userName, email, password, repeatedPassword, userCep, neighborhoodName, streetName, number, cityId, this.institutionId);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        usersController.deleteSelectedUser(this.institutionId);
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        String search = this.getjSearchTextField().getText();

        this.loadDataWithSearch(this.institutionId, search);
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void loadData(long institutionId){
        this.usersController.loadUsers(institutionId);
        this.usersController.loadCountries();
    }
    
    private void loadDataWithSearch(long institutionId, String search){
        this.usersController.loadUsersWithSearch(institutionId, search);
    }
    
    public JButton getjButtonBack() {
        return jButtonBack;
    }

    public void setjButtonBack(JButton jButtonBack) {
        this.jButtonBack = jButtonBack;
    }

    public JButton getjButtonRegister() {
        return jButtonRegister;
    }

    public void setjButtonRegister(JButton jButtonRegister) {
        this.jButtonRegister = jButtonRegister;
    }

    public JTextField getjCEPTextField() {
        return jCEPTextField;
    }

    public void setjCEPTextField(JTextField jCEPTextField) {
        this.jCEPTextField = jCEPTextField;
    }

    public JComboBox getjCityComboBox() {
        return jCityComboBox;
    }

    public void setjCityComboBox(JComboBox jCityComboBox) {
        this.jCityComboBox = jCityComboBox;
    }

    public JComboBox getjCountryComboBox() {
        return jCountryComboBox;
    }

    public void setjCountryComboBox(JComboBox jCountryComboBox) {
        this.jCountryComboBox = jCountryComboBox;
    }

    public JButton getjDeleteButton() {
        return jDeleteButton;
    }

    public void setjDeleteButton(JButton jDeleteButton) {
        this.jDeleteButton = jDeleteButton;
    }

    public JTextField getjNameTextField2() {
        return jNameTextField2;
    }

    public void setjNameTextField2(JTextField jNameTextField2) {
        this.jNameTextField2 = jNameTextField2;
    }

    public JTextField getjNameTextField3() {
        return jEmailTextField;
    }

    public void setjNameTextField3(JTextField jNameTextField3) {
        this.jEmailTextField = jNameTextField3;
    }

    public JTextField getjNeighborhoodNameTextField() {
        return jNeighborhoodNameTextField;
    }

    public void setjNeighborhoodNameTextField(JTextField jNeighborhoodNameTextField) {
        this.jNeighborhoodNameTextField = jNeighborhoodNameTextField;
    }

    public JTextField getjNumberTextField() {
        return jNumberTextField;
    }

    public void setjNumberTextField(JTextField jNumberTextField) {
        this.jNumberTextField = jNumberTextField;
    }

    public JButton getjSearchButton() {
        return jSearchButton;
    }

    public void setjSearchButton(JButton jSearchButton) {
        this.jSearchButton = jSearchButton;
    }

    public JTextField getjSearchTextField() {
        return jSearchTextField;
    }

    public void setjSearchTextField(JTextField jSearchTextField) {
        this.jSearchTextField = jSearchTextField;
    }

    public JComboBox getjStateComboBox() {
        return jStateComboBox;
    }

    public void setjStateComboBox(JComboBox jStateComboBox) {
        this.jStateComboBox = jStateComboBox;
    }

    public JTextField getjStreetTextField() {
        return jStreetTextField;
    }

    public void setjStreetTextField(JTextField jStreetTextField) {
        this.jStreetTextField = jStreetTextField;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public JTextField getjPasswordTextField() {
        return jPasswordTextField;
    }

    public void setjPasswordTextField(JTextField jPasswordTextField) {
        this.jPasswordTextField = jPasswordTextField;
    }

    public JTextField getjRepeatedPasswordTextField() {
        return jRepeatedPasswordTextField;
    }

    public void setjRepeatedPasswordTextField(JTextField jRepeatedPasswordTextField) {
        this.jRepeatedPasswordTextField = jRepeatedPasswordTextField;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextField getjUserNameTextField() {
        return jUserNameTextField;
    }

    public JTextField getjEmailTextField() {
        return jEmailTextField;
    }

    public void setjEmailTextField(JTextField jEmailTextField) {
        this.jEmailTextField = jEmailTextField;
    }

    public void setjUserNameTextField(JTextField jUserNameTextField) {
        this.jUserNameTextField = jUserNameTextField;
    }
    
    public void clearInputs(){
        jNameTextField2.setText("");
        jUserNameTextField.setText("");
        jPasswordTextField.setText("");
        jRepeatedPasswordTextField.setText("");
        jCEPTextField.setText("");
        jNeighborhoodNameTextField.setText("");
        jStreetTextField.setText("");
        jNumberTextField.setText("");
        jSearchTextField.setText("");
        jEmailTextField.setText("");

        jCountryComboBox.setSelectedIndex(0);
        
        jStateComboBox.removeAllItems();
        jStateComboBox.addItem(new ComboItem(0L, "Estado"));

        jCityComboBox.removeAllItems();
        jCityComboBox.addItem(new ComboItem(0L, "Cidade"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JTextField jCEPTextField;
    private javax.swing.JComboBox jCityComboBox;
    private javax.swing.JComboBox jCountryComboBox;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JTextField jEmailTextField;
    private javax.swing.JTextField jNameTextField2;
    private javax.swing.JTextField jNeighborhoodNameTextField;
    private javax.swing.JTextField jNumberTextField;
    private javax.swing.JTextField jPasswordTextField;
    private javax.swing.JTextField jRepeatedPasswordTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchTextField;
    private javax.swing.JComboBox jStateComboBox;
    private javax.swing.JTextField jStreetTextField;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jUserNameTextField;
    // End of variables declaration//GEN-END:variables
}
