/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.facens.upx2.smartgarden.view.form;

import com.facens.upx2.smartgarden.controller.VolunteersController;
import com.facens.upx2.smartgarden.controller.helper.VolunteersControllerHelper;
import com.facens.upx2.smartgarden.interfaces.AddressScreen;
import com.facens.upx2.smartgarden.model.helper.domain.ComboItem;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author gusta
 */
public class VolunteersScreen extends javax.swing.JFrame implements AddressScreen {
    
    private VolunteersController volunteersController;
    private VolunteersControllerHelper volunteersControllerHelper;
    private Long institutionId;
        
    /**
     * Creates new form UserScreen
     */
    public VolunteersScreen(long institutionId){
        setUndecorated(true); 
        initComponents();  
                
        setSize(1600, 754);
        setLocationRelativeTo(null);
        setResizable(false);
        
        this.volunteersControllerHelper = new VolunteersControllerHelper(this);
        this.volunteersController = new VolunteersController(volunteersControllerHelper, this);
        
        this.institutionId = institutionId;
                
        this.loadData(this.institutionId);
        
        BackgroundImage.setIcon( new javax.swing.ImageIcon( getClass().getResource("/com/facens/upx2/smartgarden/view/images/Volunteers.png") ) );
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VolunteersScreen.class.getName());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jCEPTextField = new javax.swing.JTextField();
        jCountryComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jStateComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jCityComboBox = new javax.swing.JComboBox<ComboItem>() ;
        jNeighborhoodNameTextField = new javax.swing.JTextField();
        jStreetTextField = new javax.swing.JTextField();
        jNumberTextField = new javax.swing.JTextField();
        jEmailTextField = new javax.swing.JTextField();
        jFullNameTextField = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jSearchButton = new javax.swing.JButton();
        jSearchTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 40, 40));
        getContentPane().add(jCEPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 170, -1));

        jCountryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um País" }));
        jCountryComboBox.setAutoscrolls(true);
        jCountryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCountryComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jCountryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, 120, -1));

        jStateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um estado" }));
        jStateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStateComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jStateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 190, -1));

        jCityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma cidade" }));
        getContentPane().add(jCityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 190, -1));
        getContentPane().add(jNeighborhoodNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, 170, -1));
        getContentPane().add(jStreetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 170, -1));
        getContentPane().add(jNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 170, -1));
        getContentPane().add(jEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 170, -1));
        getContentPane().add(jFullNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, 170, -1));

        jButtonRegister.setText("Cadastrar Voluntário");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        jDeleteButton.setText("Excluir Voluntário Selecionado");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 510, -1, -1));

        jSearchButton.setText("Buscar");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 540, -1, -1));
        getContentPane().add(jSearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 170, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Email", "Nome Completo", "CEP", "Cidade", "Bairro", "Rua", "Número", "Data"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, 930, 140));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/facens/upx2/smartgarden/view/images/Volunteers.png"))); // NOI18N
        getContentPane().add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 754));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jCountryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCountryComboBoxActionPerformed
        Object selectedItem = jCountryComboBox.getSelectedItem();

        if(selectedItem instanceof ComboItem comboItem){
            long countryId = comboItem.getId();
            this.volunteersController.loadStatesByCountryId(countryId);
        }
    }//GEN-LAST:event_jCountryComboBoxActionPerformed

    private void jStateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStateComboBoxActionPerformed
        Object selectedItem = jStateComboBox.getSelectedItem();

        if(selectedItem instanceof ComboItem comboItem){
            long stateId = comboItem.getId();
            this.volunteersController.loadCitiesByStateId(stateId);
        }
    }//GEN-LAST:event_jStateComboBoxActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        String name = this.getjFullNameTextField().getText();
        String email = this.getjEmailTextField().getText();
        String userCep = this.getjCEPTextField().getText();
        String neighborhoodName = this.getjNeighborhoodNameTextField().getText();
        String streetName = this.getjStreetTextField().getText();
        String number = this.getjNumberTextField().getText().trim();
        Long cityId = 0L;

        Object selectedItem = jCityComboBox.getSelectedItem();

        if(selectedItem instanceof ComboItem comboItem){
            cityId = comboItem.getId();
        }

        this.volunteersController.registerVolunteer(name, email, userCep, neighborhoodName, streetName, number, cityId, this.institutionId);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        volunteersController.deleteSelectedUser(this.institutionId);
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        String search = this.getjSearchTextField().getText();

        this.loadDataWithSearch(this.institutionId, search);
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void loadData(long institutionId){
        this.volunteersController.loadVolunteers(institutionId);
        this.volunteersController.loadCountries();
    }
    
    private void loadDataWithSearch(long institutionId, String search){
        this.volunteersController.loadVolunteersWithSearch(institutionId, search);
    }
    
    public JButton getjButtonBack() {
        return jButtonBack;
    }

    public void setjButtonBack(JButton jButtonBack) {
        this.jButtonBack = jButtonBack;
    }

    public JButton getjButtonRegister() {
        return jButtonRegister;
    }

    public void setjButtonRegister(JButton jButtonRegister) {
        this.jButtonRegister = jButtonRegister;
    }

    public JButton getjDeleteButton() {
        return jDeleteButton;
    }

    public void setjDeleteButton(JButton jDeleteButton) {
        this.jDeleteButton = jDeleteButton;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextField getjCEPTextField() {
        return jCEPTextField;
    }

    public void setjCEPTextField(JTextField jCEPTextField) {
        this.jCEPTextField = jCEPTextField;
    }

     public JComboBox getjStateComboBox() {
        return jStateComboBox;
    }

    public void setjStateComboBox(JComboBox jStateComboBox) {
        this.jStateComboBox = jStateComboBox;
    }

    public JComboBox getjCityComboBox() {
        return jCityComboBox;
    }

    public void setjCityComboBox(JComboBox jCityComboBox) {
        this.jCityComboBox = jCityComboBox;
    }

    public JComboBox getjCountryComboBox() {
        return jCountryComboBox;
    }

    public void setjCountryComboBox(JComboBox jCountryComboBox) {
        this.jCountryComboBox = jCountryComboBox;
    }

    public JTextField getjEmailTextField() {
        return jEmailTextField;
    }

    public void setjEmailTextField(JTextField jEmailTextField) {
        this.jEmailTextField = jEmailTextField;
    }

    public JTextField getjFullNameTextField() {
        return jFullNameTextField;
    }

    public void setjFullNameTextField(JTextField jFullNameTextField) {
        this.jFullNameTextField = jFullNameTextField;
    }

    public JTextField getjNeighborhoodNameTextField() {
        return jNeighborhoodNameTextField;
    }

    public void setjNeighborhoodNameTextField(JTextField jNeighborhoodNameTextField) {
        this.jNeighborhoodNameTextField = jNeighborhoodNameTextField;
    }

    public JTextField getjNumberTextField() {
        return jNumberTextField;
    }

    public void setjNumberTextField(JTextField jNumberTextField) {
        this.jNumberTextField = jNumberTextField;
    }

    public JButton getjSearchButton() {
        return jSearchButton;
    }

    public void setjSearchButton(JButton jSearchButton) {
        this.jSearchButton = jSearchButton;
    }

    public JTextField getjSearchTextField() {
        return jSearchTextField;
    }

    public void setjSearchTextField(JTextField jSearchTextField) {
        this.jSearchTextField = jSearchTextField;
    }

    public JTextField getjStreetTextField() {
        return jStreetTextField;
    }

    public void setjStreetTextField(JTextField jStreetTextField) {
        this.jStreetTextField = jStreetTextField;
    }
    
    public void clearInputs(){
        jFullNameTextField.setText("");
        jCEPTextField.setText("");
        jNeighborhoodNameTextField.setText("");
        jStreetTextField.setText("");
        jNumberTextField.setText("");
        jSearchTextField.setText("");

        jCountryComboBox.setSelectedIndex(0);
        
        jStateComboBox.removeAllItems();
        jStateComboBox.addItem(new ComboItem(0L, ""));

        jCityComboBox.removeAllItems();
        jCityComboBox.addItem(new ComboItem(0L, ""));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JTextField jCEPTextField;
    private javax.swing.JComboBox jCityComboBox;
    private javax.swing.JComboBox jCountryComboBox;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JTextField jEmailTextField;
    private javax.swing.JTextField jFullNameTextField;
    private javax.swing.JTextField jNeighborhoodNameTextField;
    private javax.swing.JTextField jNumberTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchTextField;
    private javax.swing.JComboBox jStateComboBox;
    private javax.swing.JTextField jStreetTextField;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
